version: "3"
services:

  server:
    build: ./server
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_URL=${POSTGRES_URL}

  client:
    build: ./client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - ${REACT_CLIENT_PORT}:${REACT_CLIENT_PORT}

  postgres:
    build: ./database
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
