version: "3"
services:

  server:
    build: ./server
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  client:
    build: ./client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}

