version: "3"
services:

  app:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NODE_ENV: production
      PORT: ${APP_PORT}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
